language: php
php:
    - 5.6

install:
    - composer install

script:
    - php vendor/bin/phpunit
    - php vendor/bin/phploc module/Balance/src
    - php vendor/bin/phpcpd module/Balance/src
    - php vendor/bin/parallel-lint module/Balance/src
