language: php
php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

addons:
    postgresql: 9.4

before_install:
    - psql -c "CREATE ROLE balance LOGIN PASSWORD 'balance'" -U postgres
    - psql -c "CREATE DATABASE balance WITH OwNER balance ENCODING = 'UTF8' TEMPLATE = template0" -U postgres
    - npm install -g bower

install:
    - make install

script:
    - make tests

after_success:
    - make reports
    - bash <(curl -s https://codecov.io/bash)

after_script:
    - make uninstall
    - make clean
