language: php
php:
    - 5.6
    - 7.0

addons:
    postgresql: "9.4"

before_install:
    - psql -c "CREATE ROLE balance LOGIN PASSWORD 'balance'" -U postgres
    - psql -c "CREATE DATABASE balance WITH OwNER balance ENCODING = 'UTF8' TEMPLATE = template0" -U postgres
    - npm install -g bower

install:
    - composer install

script:
    - php vendor/bin/phinx migrate
    - make tests
    - php vendor/bin/phinx migrate -t0

after_success:
    - bash <(curl -s https://codecov.io/bash)
