language: php
php:
    - 5.6
    - 7.0

addons:
    postgresql: "9.4"

before_install:
    - psql -c "CREATE ROLE balance LOGIN PASSWORD 'balance'" -U postgres
    - psql -c "CREATE DATABASE balance WITH OwNER balance ENCODING = 'UTF8' TEMPLATE = template0" -U postgres
    - npm install -g bower

install:
    - composer install

script:
    - php vendor/bin/phinx migrate
    - php vendor/bin/phpunit --coverage-text=php://stdout --coverage-clover=coverage.xml --whitelist module/Balance/src
    - php vendor/bin/phploc module/Balance/src
    - php vendor/bin/phpcpd module/Balance/src
    - php vendor/bin/parallel-lint module/Balance/src
    - php vendor/bin/phpcs --standard=phpcs.xml --runtime-set ignore_warnings_on_exit true --encoding=utf-8 --colors module/Balance/src
    - php vendor/bin/php-cs-fixer fix --config-file=phpcs.php --dry-run --diff
    - php vendor/bin/phpmd module/Balance/src text phpmd.xml
    - php vendor/bin/phinx migrate -t0

after_success:
    - bash <(curl -s https://codecov.io/bash)
