language: php
php:
    - 5.6

addons:
    postgresql: "9.4"

before_script:
    - psql -c "CREATE ROLE balance LOGIN PASSWORD 'balance'" -U postgres
    - psql -c "CREATE DATABASE balance WITH OwNER balance ENCODING = 'UTF8' TEMPLATE = template0" -U postgres

install:
    - composer install

script:
    - php vendor/bin/phpunit
    - php vendor/bin/phploc module/Balance/src
    - php vendor/bin/phpcpd module/Balance/src
    - php vendor/bin/parallel-lint module/Balance/src
    - php vendor/bin/phpcs --standard=phpcs.xml --encoding=utf-8 --colors module/Balance/src
    - php vendor/bin/php-cs-fixer fix --config-file=phpcs.php --dry-run --diff
    - php vendor/bin/phpmd module/Balance/src text phpmd.xml
